name: Build

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-2019

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Clone lib repo
        uses: actions/checkout@v2
        with:
          repository: PowerBall253/lib
          token: ${{secrets.ACCESS_TOKEN}}
          path: lib

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: cd to workspace
        run: cd ${{github.workspace}}

      - name: Configure CMake
        run: |
          cmake -B build -G 'MSYS Makefiles'

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Rename
        run: mv build\Release\EternalTextureCompressor.exe EternalTextureCompressor-Windows.exe

      - name: Upload Exe
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file_glob: true
          file: ${{github.workspace}}/EternalTextureCompressor-Windows.exe
          tag: ${{github.ref}}

  linux-build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Clone lib repo
        uses: actions/checkout@v2
        with:
          repository: PowerBall253/lib
          token: ${{secrets.ACCESS_TOKEN}}
          path: lib

      - name: cd to workspace
        run: cd ${{github.workspace}}

      - name: Configure CMake
        run: |
          export CC=gcc-10
          export CXX=g++-10
          cmake -B build

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Rename and strip binary
        run: |
          mv build/EternalTextureCompressor EternalTextureCompressor-Linux
          strip EternalTextureCompressor-Linux

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: |
            ${{github.workspace}}/EternalTextureCompressor-Linux

  macos-build:
    runs-on: macos-10.15

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Clone lib repo
        uses: actions/checkout@v2
        with:
          repository: PowerBall253/lib
          token: ${{secrets.ACCESS_TOKEN}}
          path: lib

      - name: cd to workspace
        run: cd ${{github.workspace}}

      - name: Configure CMake
        run: |
          cmake -B build

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Rename and strip binary
        run: |
          mv build/EternalTextureCompressor EternalTextureCompressor-macOS
          strip EternalTextureCompressor-macOS

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file_glob: true
          file: ${{github.workspace}}/EternalTextureCompressor-macOS
          tag: ${{github.ref}}
